[build-system]
requires = ["scikit-build-core[rich,pyproject]", "cmake>=3.15", "ninja"] # Added cmake and ninja
build-backend = "scikit_build_core.build"

[project]
name = "pyrjmcmc"
version = "0.0.1"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]

# Add this new section for scikit-build-core configuration
[tool.scikit-build]
# Pass direct CMake arguments to help FindPython
# These use environment variables that cibuildwheel sets up for each Python version.
cmake.args = [
    "-DPython_INCLUDE_DIRS=$ENV{PYTHON_INCLUDE_DIR}",
    "-DPython_LIBRARIES=$ENV{PYTHON_LIB}",
    "-DPython3_INCLUDE_DIRS=$ENV{PYTHON_INCLUDE_DIR}", # For Python 3 specific FindPython calls
    "-DPython3_LIBRARIES=$ENV{PYTHON_LIB}",            # For Python 3 specific FindPython calls
]
