# pyproject.toml

[build-system]
# scikit-build-core will inject cmake and ninja, so you don't strictly need them here,
# but keeping them doesn't hurt and explicitly states requirements.
# The warning from scikit-build-core is harmless if they are present.
# Also, remove the '[rich,pyproject]' extra if you don't specifically need it for build-system itself.
# Often just "scikit-build-core>=0.11.0" is sufficient.
requires = ["scikit-build-core>=0.11.0", "cmake>=3.15", "ninja"]
build-backend = "scikit_build_core.build"

[project]
name = "pyrjmcmc"
version = "0.0.1"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]


# --- Linux-specific configuration for cibuildwheel ---
[tool.cibuildwheel.linux]
# This command is still necessary to install system-level packages like Python development headers and SWIG.
before-build = "yum update -y && yum install -y python3-devel swig"
# Add these CMake definitions.
# These variables directly hint CMake's FindPython module where to look.
# cibuildwheel sets these environment variables for the current Python interpreter.
cmake.define = {
    # Hints to CMake's FindPython/FindPython3 modules
    PYTHON_EXECUTABLE = "$ENV{PYTHON_DOT_VERSION_EXE}", # e.g., /opt/python/cp39-cp39/bin/python3.9
    PYTHON_INCLUDE_DIR = "$ENV{PYTHON_INCLUDE_DIR}", # e.g., /opt/python/cp39-cp39/include/python3.9/
    PYTHON_LIBRARY = "$ENV{PYTHON_LIB}", # e.g., /opt/python/cp39-cp39/lib/libpython3.9.so
    Python3_EXECUTABLE = "$ENV{PYTHON_DOT_VERSION_EXE}",
    Python3_INCLUDE_DIR = "$ENV{PYTHON_INCLUDE_DIR}",
    Python3_LIBRARY = "$ENV{PYTHON_LIB}",
}
# If you have macOS or Windows configurations, they would go here too.
