# pyproject.toml

[build-system]
# scikit-build-core will inject cmake and ninja, so you don't strictly need them here,
# but keeping them doesn't hurt and explicitly states requirements.
# The warning from scikit-build-core is harmless if they are present.
# Also, remove the '[rich,pyproject]' extra if you don't specifically need it for build-system itself.
# Often just "scikit-build-core>=0.11.0" is sufficient.
requires = ["scikit-build-core>=0.11.0", "cmake>=3.15", "ninja"]
build-backend = "scikit_build_core.build"

[project]
name = "pyrjmcmc"
version = "0.0.1"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]

# REMOVE THIS ENTIRE SECTION:
# [tool.scikit-build]
# cmake.args = [
#     "-DPython_INCLUDE_DIRS=$ENV{PYTHON_INCLUDE_DIR}",
#     "-DPython_LIBRARIES=$ENV{PYTHON_LIB}",
#     "-DPython3_INCLUDE_DIRS=$ENV{PYTHON_INCLUDE_DIR}", # For Python 3 specific FindPython calls
#     "-DPython3_LIBRARIES=$ENV{PYTHON_LIB}",            # For Python 3 specific FindPython calls
# ]


# --- Linux-specific configuration for cibuildwheel ---
[tool.cibuildwheel.linux]
# This command is still necessary to install system-level packages like Python development headers and SWIG.
before-build = "yum update -y && yum install -y python3-devel swig"

# If you have macOS or Windows configurations, they would go here too.
