name: Build and Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4

      # Setup SWIG - This step is correctly placed and configured.
      - name: Setup SWIG
        uses: mmomtchev/setup-swig@v4
        with:
          branch: jse

      - name: Verify SWIG
        run: swig -version
    
      # Set up Python for cibuildwheel itself (on the host runner).
      # cibuildwheel is a Python tool and needs a Python environment to run.
      - name: Set up Python for cibuildwheel
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22
        with:
          output-dir: wheelhouse
        env:
          # IMPORTANT: Removed CIBW_ENVIRONMENT_SCRIPT_LINUX as it seems to not be executing correctly.
          # We're now using CIBW_BEFORE_BUILD_LINUX for environment setup.

          # CIBW_BEFORE_BUILD_LINUX executes a shell script inside the build container
          # right before the wheel build starts. This is a reliable place to set
          # environment variables for CMake.
          CIBW_BEFORE_BUILD_LINUX: |
            set -x # Enable shell debugging to see executed commands
            export PYTHON_ROOT_DIR="$(dirname "$(dirname "$PYTHON_BIN")")"
            export Python3_ROOT_DIR="$PYTHON_ROOT_DIR"
            export Python3_INCLUDE_DIR="$PYTHON_INCLUDE_DIR"
            export Python3_LIBRARY="$PYTHON_LIB"
            echo "DEBUG: PYTHON_ROOT_DIR set to: $PYTHON_ROOT_DIR"
            echo "DEBUG: Python3_INCLUDE_DIR set to: $Python3_INCLUDE_DIR"
            echo "DEBUG: Python3_LIBRARY set to: $Python3_LIBRARY"
            # Add a dummy command to ensure the script doesn't exit prematurely if no other commands are needed
            true

          # CIBW_CMAKE_OPTIONS can still be used for other specific CMake flags if needed,
          # but the Python path setting should now be handled by CIBW_BEFORE_BUILD_LINUX.
          # CIBW_CMAKE_OPTIONS: >
          #   -DPython3_INCLUDE_DIR="$PYTHON_INCLUDE_DIR"
          #   -DPython3_LIBRARY="$PYTHON_LIB"
          
          CIBW_SKIP: pp* cp36* cp37* cp38* *-win32 *-manylinux_i686 *-musllinux_*
          
          MACOSX_DEPLOYMENT_TARGET: 14

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-wheelhouse
          path: wheelhouse

  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up environment
        run: |
          python -m pip install scikit-build-core build

      - name: Build and check sdist
        run: |
          python -m build --sdist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz
          name: sourcedist

  deploy:
    runs-on: ubuntu-latest
    needs: [build-wheel, build-sdist]
    if: ${{ startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch' }}
    environment: deployment
    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.3
