name: Build and Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup SWIG
        uses: mmomtchev/setup-swig@v4
        with:
          branch: jse

      - name: Verify SWIG
        run: swig -version
    
      - name: Set up Python for cibuildwheel
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22
        with:
          output-dir: wheelhouse
        env:
          # CIBW_ENVIRONMENT_LINUX is still useful for general environment vars,
          # but for CMake specifics, CIBW_CMAKE_OPTIONS is often more direct.
          # We'll keep it for now as it doesn't hurt.
          CIBW_ENVIRONMENT_LINUX: >
            Python_ROOT_DIR="$(dirname $(dirname "$PYTHON_BIN"))"
            Python3_ROOT_DIR="$(dirname $(dirname "$PYTHON_BIN"))"

          # This is the new crucial part: Pass Python include/library paths to CMake.
          # CIBW_CMAKE_OPTIONS allows passing extra arguments directly to CMake.
          # -DPython3_INCLUDE_DIR points to the Python C headers.
          # -DPython3_LIBRARY points to the Python shared library.
          # We use "$PYTHON_INCLUDE_DIR" and "$PYTHON_LIB" which are also provided by cibuildwheel.
          CIBW_CMAKE_OPTIONS: >
            -DPython3_INCLUDE_DIR="$PYTHON_INCLUDE_DIR"
            -DPython3_LIBRARY="$PYTHON_LIB"
          
          CIBW_SKIP: pp* cp36* cp37* cp38* *-win32 *-manylinux_i686 *-musllinux_*
          
          MACOSX_DEPLOYMENT_TARGET: 14

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-wheelhouse
          path: wheelhouse

  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up environment
        run: |
          python -m pip install scikit-build-core build

      - name: Build and check sdist
        run: |
          python -m build --sdist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz
          name: sourcedist

  deploy:
    runs-on: ubuntu-latest
    needs: [build-wheel, build-sdist]
    if: ${{ startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch' }}
    environment: deployment
    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.3
