name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup SWIG
        uses: mmomtchev/setup-swig@v4 # Use the latest version or a specific one
        with:
          branch: jse

      - name: Verify
        run: swig -version

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with uv
        run: uv pip install pytest  --system

      - name: Install the project
        run: uv sync --all-extras --dev
  
      - name: Run tests
        run: |
          uv run pytest 
